name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '18.x'

      - name: 'install'
        run: npm i

      - name: 'build'
        run: npm run build

      - name: 'show structure'
        run: ls -al
